import Web3 from 'web3';

var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
let manufacturerABI=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"BrandAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_mid","type":"uint256"},{"name":"_name","type":"bytes32"},{"name":"_country","type":"string"},{"name":"_phone","type":"int256"},{"name":"_website","type":"string"}],"name":"setBrand","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getBrands","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_mid","type":"uint256"}],"name":"getBrand","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"string"},{"name":"","type":"int256"},{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countBrands","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
let manufacturerAddress='0x6870d6e537365008d62d5906d729ee2b1d64a4a2';
const manufacturerContract=web3.eth.contract(manufacturerABI).at(manufacturerAddress);

let vehicleABI=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"carAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_carid","type":"uint256"},{"name":"_model","type":"string"},{"name":"_year","type":"int256"},{"name":"_value","type":"int256"},{"name":"_active","type":"bool"},{"name":"_mid","type":"uint256"}],"name":"setCar","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getCars","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_carid","type":"uint256"}],"name":"getCar","outputs":[{"name":"","type":"uint256"},{"name":"","type":"string"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bool"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countCars","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_model","type":"string"}],"name":"getVehicleByModel","outputs":[{"name":"","type":"uint256"},{"name":"","type":"string"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bool"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
let vehicleAddress='0xd37093c337b1fde6176ad26e902808dcbd897dc5';
const vehicleContract=web3.eth.contract(vehicleABI).at(vehicleAddress);
web3.eth.defaultAccount = web3.eth.accounts[0]


export {manufacturerContract,vehicleContract};
