import Web3 from 'web3';

//const web3=new Web3(new Web3.providers.HttpProvider("https://api.myetherapi.com/eth"));
var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
let manufacturerABI=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"BrandAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_mid","type":"uint256"},{"name":"_name","type":"bytes32"},{"name":"_country","type":"bytes32"},{"name":"_phone","type":"int256"},{"name":"_website","type":"bytes32"}],"name":"setBrand","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getBrands","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_mid","type":"uint256"}],"name":"getManufacturerById","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countBrands","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_name","type":"string"}],"name":"getManufacturerByName","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let manufacturerAddress='0xcbf939cdf3e61a07c3b0069efbe72cf380f9c9c7';
const manufacturerContract=web3.eth.contract(manufacturerABI).at(manufacturerAddress);

let vehicleABI=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"carAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_carid","type":"uint256"},{"name":"_model","type":"bytes32"},{"name":"_year","type":"int256"},{"name":"_value","type":"int256"},{"name":"_active","type":"bool"},{"name":"_mid","type":"uint256"}],"name":"setCar","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getCars","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_carid","type":"uint256"}],"name":"getCar","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bool"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countCars","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_model","type":"string"}],"name":"getVehicleByModel","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bool"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_vehiclesID","type":"uint256"}],"name":"isAVehicles","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let vehicleAddress='0x18e2ec72dce09ded415ee9731ea9e029cc197bbd';
const vehicleContract=web3.eth.contract(vehicleABI).at(vehicleAddress);

let scrappageabi=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"scrapAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_carid","type":"uint256"},{"name":"_scrapDate","type":"int256"}],"name":"setScraps","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getScraps","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_carid","type":"uint256"}],"name":"getScrap","outputs":[{"name":"","type":"uint256"},{"name":"","type":"int256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countScraps","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let scrappageAddress='0x48d1ed7c2d76f88e30fcbbe5a6f00ecba97a265d';
const scrappageContract=web3.eth.contract(scrappageabi).at(scrappageAddress);

let dealerabi=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"dealerAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_did","type":"uint256"},{"name":"_dname","type":"bytes32"},{"name":"_dphone","type":"int256"},{"name":"_dstreet","type":"bytes32"},{"name":"_dtown","type":"bytes32"},{"name":"_dcounty","type":"bytes32"}],"name":"setDealer","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getDealers","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_did","type":"uint256"}],"name":"getDealer","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countDealers","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_dname","type":"string"}],"name":"getDealerByName","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_dealerID","type":"uint256"}],"name":"isADealer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let dealerAddress='0x7bfdad318006bb23e98123b108863c12c4abff42';
const dealerContract=web3.eth.contract(dealerabi).at(dealerAddress);

let transactionabi=[{"constant":true,"inputs":[],"name":"count","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"transactionAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_tid","type":"uint256"},{"name":"_tdate","type":"uint256"},{"name":"_did","type":"uint256"},{"name":"_carid","type":"uint256"},{"name":"_cid","type":"uint256"},{"name":"_buyOrSell","type":"bytes32"},{"name":"_tamount","type":"int256"},{"name":"_tmileage","type":"int256"}],"name":"setTransaction","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getTransactions","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_tid","type":"uint256"}],"name":"getTransactionDetail","outputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"int256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_tid","type":"uint256"}],"name":"getTransactionRelations","outputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countTransactions","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_carid","type":"uint256"}],"name":"getTransctionsForCar","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_customerId","type":"uint256"}],"name":"getCurrentCarForCust","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_customerId","type":"uint256"}],"name":"getPrevousCarForCust","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"values","type":"uint256[]"},{"name":"value","type":"uint256"}],"name":"IndexOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let transactionAddress='0x0f78f157f9fb0beff48d74769c534030a4d948d4';
const transactionContract=web3.eth.contract(transactionabi).at(transactionAddress);

let customerabi=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"clientAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_cid","type":"uint256"},{"name":"_cname","type":"bytes32"},{"name":"_cdob","type":"int256"},{"name":"_clicencenum","type":"int256"},{"name":"_cstreet","type":"bytes32"},{"name":"_ctown","type":"bytes32"},{"name":"_ccounty","type":"bytes32"}],"name":"setClient","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getClients","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_cid","type":"uint256"}],"name":"getClient","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countClients","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_cname","type":"bytes32"}],"name":"getCustomerByName","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_customerID","type":"uint256"}],"name":"isACustomer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let customerAddress='0xaacb25574e908d919c3c80717bcd916bf87df0d8';
const customerContract=web3.eth.contract(customerabi).at(customerAddress);

let serviceCenterabi=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"serviceCentAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_SCid","type":"uint256"},{"name":"_SCname","type":"bytes32"},{"name":"_SCphone","type":"int256"},{"name":"_SCstreet","type":"bytes32"},{"name":"_SCtown","type":"bytes32"},{"name":"_SCcounty","type":"bytes32"}],"name":"setServiceCent","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getServiceCents","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_SCid","type":"uint256"}],"name":"getServiceCent","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countServiceCents","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_serviceCenterID","type":"uint256"}],"name":"isAServiceCenter","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_SCname","type":"string"}],"name":"getServiceCentersByName","outputs":[{"name":"","type":"uint256"},{"name":"","type":"bytes32"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"}]
let serviceCenterAddress='0x1cd3dfc0d20c85fbbc1a845212ed1c4d12069378';
const serviceCenterContract=web3.eth.contract(serviceCenterabi).at(serviceCenterAddress);

let vehileServiceabi=[{"constant":true,"inputs":[],"name":"count","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"serviceAccts","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"args","type":"bytes32[]"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":false,"inputs":[{"name":"_Sid","type":"uint256"},{"name":"_Sdate","type":"int256"},{"name":"_SCid","type":"uint256"},{"name":"_carid","type":"uint256"},{"name":"_Smileage","type":"int256"},{"name":"_SrepairType","type":"bytes32"},{"name":"_SrepairDetails","type":"bytes32"},{"name":"_Scost","type":"int256"}],"name":"setServicebyID","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"getServices","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_Sid","type":"uint256"}],"name":"getService","outputs":[{"name":"","type":"uint256"},{"name":"","type":"int256"},{"name":"","type":"int256"},{"name":"","type":"bytes32"},{"name":"","type":"bytes32"},{"name":"","type":"int256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_Sid","type":"uint256"}],"name":"getServiceRelations","outputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countServices","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_carid","type":"uint256"}],"name":"getServiceForCar","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"source","type":"string"}],"name":"stringToBytes32","outputs":[{"name":"result","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]
let vehileServiceAddress='0xfe788cb44d4b98cd93729b6ef9482db1227bfb09';
const vehileServiceContract=web3.eth.contract(vehileServiceabi).at(vehileServiceAddress);

web3.eth.defaultAccount = web3.eth.accounts[0];

export {manufacturerContract,vehicleContract,scrappageContract,dealerContract,transactionContract,customerContract,serviceCenterContract,vehileServiceContract};
